import { useEffect } from 'react';

function TermsAndConditions({ onNavigate }) {
  useEffect(() => {
    document.title = "Terms & Conditions | Triventa Exports";
  }, []);

  return (
    <div className="legal-page-container animate-fade-in">
      <header className="legal-header">
        <div className="legal-header-content">
          <div className="logo-container">
            <span className="logo-image" aria-label="Triventa Exports Logo" role="img"></span>
            <span className="logo-text">TRIVENTA EXPORTS</span>
          </div>
          <button type="button" className="legal-back-btn" onClick={() => onNavigate('/')}>
            ← Back to Home
          </button>
        </div>
      </header>

      <main className="legal-content-wrapper">
        <h1 className="legal-title">Terms &amp; Conditions</h1>
        <p className="legal-last-updated">Last Updated: June 23, 2026</p>

        <section className="legal-section-block">
          <p>
            Welcome to the website of Triventa Exports Private Limited (&ldquo;Triventa,&rdquo; &ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;). By accessing our website, simulating bulk shipments on our FOB calculator, or requesting specialty green coffee samples, you agree to comply with and be bound by the following Terms &amp; Conditions.
          </p>
        </section>

        <section className="legal-section-block">
          <h2>1. Nature of Services &amp; Disclaimers</h2>
          <p>
            Triventa is a registered wholesale commercial exporter of unroasted green coffee beans. We do not sell roasted coffee or consumer-packaged retail bags through this platform.
          </p>
          <ul>
            <li><strong>FOB Pricing Estimates:</strong> All estimations, freight volumes, and container capacities generated by our Custom FOB Export Calculator are simulated projections.Sourcing values are tied directly to daily local coffee board auctions in Chikkamagaluru, India, and are subject to immediate fluctuations. Final contract rates are issued only upon formal commercial proforma invoice.</li>
            <li><strong>Customs and Transport:</strong> We dispatch containers from the Port of Mangalore (NMPT) under DGFT export rules. International deliveries are governed by shipping line bills of lading and IncoTerms (typically FOB or CIF).</li>
          </ul>
        </section>

        <section className="legal-section-block">
          <h2>2. Cupping Sample Reservations</h2>
          <p>We supply 300g raw green coffee samples globally for roaster evaluations, subject to the following rules:</p>
          <ul>
            <li><strong>Business Verification:</strong> Samples are reserved strictly for registered coffee roasters, wholesale importers, and coffee brokers. We reserve the right to decline sample requests from retail consumers or invalid business entities.</li>
            <li><strong>Tracking Codes:</strong> The tracking codes generated by our reservation portal (e.g. <code>TES-XXXXXXX</code>) signify origin inventory allocations and are not binding contracts of dispatch. We verify credentials prior to logistics shipping.</li>
            <li><strong>Customs, Shipping &amp; Duty Liabilities:</strong> Cupping samples are subject to sample and freight shipping charges, which must be prepaid or billed to the buyer's shipping account (DHL/FedEx) as coordinated with our trade desk. In addition, buyers are fully responsible for any destination country customs clearances, phytosanitary import certifications, or local cargo import tariffs.</li>
          </ul>
        </section>

        <section className="legal-section-block">
          <h2>3. Regulatory &amp; Export Compliance</h2>
          <p>All export sales agreements are filed and processed under the regulations of the Government of India:</p>
          <ul>
            <li><strong>Coffee Board Sourcing:</strong> All lots are verified under our registered RCMC License (Certificate No: 3463) with the Coffee Board of India.</li>
            <li><strong>ICEGATE Filings:</strong> Customs declarations and shipping bills are electronically filed under our Import Export Code (IEC: AAMCT6839P) and ICEGATE ID (AAMCT6839PPIE000).</li>
          </ul>
        </section>

        <section className="legal-section-block">
          <h2>4. Intellectual Property</h2>
          <p>
            All content, layout designs, catalog schemas, calculators, branding elements, and masking graphics (including our logo mask and custom vectors) are the intellectual property of Triventa Exports Private Limited. No content may be reproduced or used for commercial purposes without our express written consent.
          </p>
        </section>

        <section className="legal-section-block">
          <h2>5. Limitation of Liability</h2>
          <p>
            Triventa will not be liable for any direct, indirect, incidental, or consequential damages arising from the use of this website, delayed sample dispatches, port delays at Mangalore, or price adjustments dictated by the global coffee auction markets.
          </p>
        </section>

        <section className="legal-section-block">
          <h2>6. Governing Law</h2>
          <p>
            These Terms &amp; Conditions are governed by and construed in accordance with the laws of the Republic of India. Any disputes arising in connection with our services, sample dispatches, or export shipments shall be subject to the exclusive jurisdiction of the competent courts in Mangalore, Karnataka, India.
          </p>
        </section>

        <section className="legal-section-block">
          <h2>7. Contact Information</h2>
          <p>For official inquiries or legal correspondence, please write to our corporate desk:</p>
          <div className="legal-contact-card">
            <p><strong>Triventa Exports Private Limited</strong></p>
            <p>Corporate Office: Mangalore, Karnataka, India</p>
            <p>CIN: U46209KA2026PTC214010 &bull; GSTIN: 29AAMCT6839P1Z5</p>
            <p>Email: <a href="mailto:info@triventaexports.com">info@triventaexports.com</a></p>
            <p>Phone / WhatsApp: <a href="tel:+919148025018">+91 91480 25018</a></p>
          </div>
        </section>
      </main>

      <footer className="legal-footer">
        <p className="copyright">&copy; 2026 Triventa Exports Private Limited. All rights reserved.</p>
      </footer>
    </div>
  );
}

export default TermsAndConditions;
